### ISSUE TITLE
能否实现SyncCall

### ISSUE THREAD

**Issue by hanxi** [xingshuo/skyline#1]
粗略看了一遍代码，应该是一个服务只有一个 goroutine，如果要实现 skynet.call 一样的效果，是不是需要做成每个消息 dispatch 时创建一个 goroutine ，是否可以用 chan 来控制一个服务同一时间只允许一个 goroutine 运行，类似用 chan 来实现 yield 和 resume，如下示例代码，没验证是否可行。

```
package main

import (
    "fmt"
    "sync"
)

func worker(id int, sem chan struct{}, wg *sync.WaitGroup) {
    defer wg.Done()
    sem <- struct{}{} // acquire semaphore
    fmt.Printf("Worker %d starts\n", id)
    // do some work here
    fmt.Printf("Worker %d ends\n", id)
    <-sem // release semaphore
}

func main() {
    sem := make(chan struct{}, 1) // create a semaphore with capacity 1
    var wg sync.WaitGroup
    for i := 0; i < 5; i++ {
        wg.Add(1)
        go worker(i, sem, &wg)
    }
    wg.Wait()
}

```

**Comment by xingshuo** [comment]
之前有按你说的思路做过类似的尝试，方案是可行的：
https://github.com/xingshuo/saber
https://github.com/xingshuo/coroutine
不过考虑到高并发场景每个请求通过独立的goroutine来处理，其性能相比只通过一个固定goroutine处理还是会差一点（在腾讯内网和知乎上有看过类似的文章，大概是由于频繁创建和销毁goroutine，无法复用协程栈导致。当然对于大部分游戏业务应该区别不大- -），调研了下，一些成熟的工业级rpc框架目前还是通过callback方式处理类似的场景，这里就没做调整

**Comment by hanxi** [comment]
谢谢解答

**Comment by xingshuo** [comment]
不客气 哈哈
